# Generated by Django 4.1 on 2022-10-01 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Expense Name')),
                ('type', models.CharField(choices=[('OTHER', 'Other'), ('TRAVEL', 'Travelling'), ('WAGES', 'Labour and wages'), ('FOOD', 'Food and drinks'), ('FUEL', 'Fuel'), ('MARKETING', 'Marketing'), ('INPUTS', 'Farm Inputs (Fertilizer, pesticides e.t.c')], default='OTHER', max_length=100, verbose_name='Category')),
                ('when', models.DateField(verbose_name='Date of expenditure')),
                ('description', models.TextField(verbose_name='Describe how you spent the funds')),
                ('amount', models.FloatField(verbose_name='Amount (in KES)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-when'],
            },
        ),
    ]
