# Generated by Django 4.1 on 2022-10-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='valid',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TRAVEL', 'Travelling'), ('WAGES', 'Labour and wages'), ('FOOD', 'Food and drinks'), ('FUEL', 'Fuel'), ('MARKETING', 'Marketing'), ('INPUTS', 'Farm Inputs (Fertilizer, pesticides e.t.c')], default='NO', max_length=100, verbose_name='Is Valid?'),
        ),
    ]
