# Generated by Django 4.1 on 2022-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='valid',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=100, verbose_name='Is Valid?'),
        ),
    ]
