# Generated by Django 4.1 on 2022-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_timestamp', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('weather_icon', models.IntegerField(null=True)),
                ('daytime', models.CharField(max_length=100)),
                ('temperature', models.FloatField(null=True)),
                ('_24_hr_temp_range', models.FloatField(null=True)),
                ('relative_humidity', models.FloatField(null=True)),
                ('wind_direction', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('uv_index', models.FloatField(null=True)),
                ('cloud_cover', models.FloatField(null=True)),
                ('cloud_ceiling', models.FloatField(null=True)),
                ('_12_hr_precipitation', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'ordering': ['-observation_timestamp'],
            },
        ),
    ]
