# Generated by Django 4.1 on 2022-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='daytime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
