# Generated by Django 4.1 on 2022-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherdata_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='_12_hr_precipitation',
            field=models.FloatField(null=True, verbose_name='Precipitation in mm'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='cloud_ceiling',
            field=models.FloatField(null=True, verbose_name='Height in metres'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='Temp in celsius'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
