# Generated by Django 4.1 on 2022-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherdata__12_hr_precipitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='epoch',
            field=models.BigIntegerField(null=True),
        ),
    ]
