# Generated by Django 4.1 on 2022-09-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherdata_epoch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='_12_hr_precipitation',
            new_name='precipitation_12_hr',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='_24_hr_temp_range',
            new_name='range_24_hr_temp',
        ),
    ]
