# Generated by Django 4.1 on 2022-09-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Product Name'),
        ),
    ]
