# Generated by Django 4.1 on 2022-09-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product_id',
            new_name='product',
        ),
    ]
