# Generated by Django 4.1 on 2022-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_product_id_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='valid',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=100, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.FloatField(default=None, verbose_name='Quantity (in kg)'),
        ),
    ]
