# Generated by Django 4.1 on 2022-09-11 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AddField(
            model_name='crop',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
