# Generated by Django 4.1 on 2022-09-11 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='when',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
