# Generated by Django 4.1 on 2022-09-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0010_alter_expense_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-when'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(verbose_name='Amount (in KES)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='Describe how you spent the funds'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='when',
            field=models.DateField(verbose_name='Date of expenditure'),
        ),
    ]
