# Generated by Django 4.1 on 2022-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_expense_options_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TRAVEL', 'Travelling'), ('WAGES', 'Labour and wages'), ('FOOD', 'Food and drinks'), ('FUEL', 'Fuel'), ('MARKETING', 'Marketing'), ('INPUTS', 'Farm Inputs (Fertilizer, pesticides e.t.c')], default='OTHER', max_length=100, verbose_name='Category'),
        ),
    ]
